# Generated by Django 4.2.11 on 2024-09-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
