# Generated by Django 5.1.2 on 2025-07-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_journalentry_soulthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mood_raw',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
